import type { Metadata } from 'next'
import { Big_Shoulders_Display, Lexend_Deca } from 'next/font/google'
import './globals.css'

const lexandDeca = Lexend_Deca({subsets: ['latin'], weight: ['400']})
const bigShouldersDisplay = Big_Shoulders_Display({subsets: ['latin'], weight: ['700']})

export const metadata: Metadata = {
  title: '3-column preview card component',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lexandDeca.className}>{children}</body>
    </html>
  )
}
